routes/web.php
<?php
/*
 *
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Home */
Route::get('/', 'PrincipalController@index');
Route::post('/votar', 'PrincipalController@createVoteAndUpdateStatusVoter')->name('principal.createVoteAndUpdateStatusVoter');
Route::post('/buscar', 'PrincipalController@voterSearch')->name('principal.voterSearch');

/* Voter Resource*/
Route::resource('votante', 'VoterController')->except(['destroy']);
Route::post('/votante/buscar', 'VoterController@searchByFilter')->name('voters.searchByFilter');

/*Candidate Resource*/
Route::resource('candidato', 'CandidateController')->except(['show']);
Route::get('/candidatos/listar', 'CandidateController@listCandidates')->name('candidate.list');
Route::post('/candidato/buscar','CandidateController@searchByFilter')->name('candidate.searchByFilter');

/* Authentication Routes*/
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

/* Last View Route*/
Route::get('/ganador', 'CandidateController@searchWinnerCandidate')->name('candidate.searchWinner');

app/Candidate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;

class Candidate extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'first_name','last_name','dni','birthday','address','email','political_party','list', 'image',
    ];

    protected $rules = [
        'first_name'=>'required|alpha',
        'last_name'=>'required|alpha',
        'birthday'=>'required|date',
        'dni'=>'required|digits_between:7,8|numeric|unique:candidates',
        'address'=>'required|string',
        'list'=>'required',
        'political_party'=>'required|string',
        'email'=>'required|email|unique:candidates',
        'image'=>'image',
    ];

    protected $messages = [
        'birthday.date'=> 'La fecha de nacimiento no es una fecha válida'
    ];

    public function getValidationRules(): array
    {
        return $this->rules;
    }

    public function getValidationMessages(): array
    {
        return $this->messages;
    }

    public function getAttribute($key)
    {
        return $this->attributes[$key];
    }

    public function setAttribute($key, $value)
    {
        $this->attributes[$key] = $value;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function vote()
    {
        return $this->hasMany(Vote::class, 'id_candidate');
    }

    public function getPoliticalParties(): array
    {
        $politicalParties = new Collection();
        $parties = Candidate::all()
            ->pluck('political_party')
            ->unique();
        foreach ($parties as $party){
            if ($party === 'White') { continue; }
            $politicalParties->push($party);
        }

        return $politicalParties->toArray();
    }

    public static function getVotesOfCandidate(): array
    {
        return DB::table('candidates')
            ->join('votes', 'candidates.id', '=', 'votes.id_candidate')
            ->select('candidates.first_name','candidates.last_name', DB::raw('count(votes.vote) as recuento'))
            ->groupBy('candidates.id')
            ->get()->toArray();
    }
    
    public static function getVotesOfCandidateWithoutWhiteVote(): array
    {
        return DB::table('candidates')
            ->join('votes', 'candidates.id', '=', 'votes.id_candidate')
            ->select('candidates.first_name','candidates.last_name','candidates.id',
                DB::raw('count(votes.vote) as countVotes'))
            ->where('candidates.last_name', '<>', 'White')
            ->where('candidates.deleted_at', null)
            ->groupBy('candidates.id')
            ->orderBy('countVotes', 'desc')
            ->get()->toArray();
    }

    public static function getCountWhiteVotes(): array
    {
        return DB::table('candidates')
            ->join('votes', 'candidates.id', '=', 'votes.id_candidate')
            ->select('candidates.first_name','candidates.last_name',
                DB::raw('count(votes.vote) as countVotes'))
            ->where('candidates.last_name', 'White')
            ->groupBy('candidates.id')
            ->get()->toArray();
    }

    public function getWinnerCandidate(): \stdClass
    {
        $candidate = self::getVotesOfCandidateWithoutWhiteVote()[0];
        $whiteVotes = self::getCountWhiteVotes()[0];
        $candidate->countVotes += $whiteVotes->countVotes;

        return $candidate;
    }
}

app/Http/Controllers/CandidateController.php
<?php

namespace App\Http\Controllers;

use App\Candidate;
use App\Repositories\Repository;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;


class CandidateController extends Controller
{
    /**
     * @var Candidate
     */
    private $candidate;

    private $candidateRepository;

    public function __construct(Candidate $candidate)
    {
        $this->middleware('auth')->except(['listCandidates', 'searchWinnerCandidate']);
        $this->candidate = new Candidate();
        $this->candidateRepository = new Repository($candidate);
    }

    public function listCandidates(): Collection
    {
        return $this->candidateRepository->getAll();
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|View
     */
    public function index()
    {
        $candidates = $this->candidateRepository->getAll();

        return view('candidate.list_candidate', compact('candidates'));
    }

    /**
     * @return View
     */
    public function create()
    {
        $politicalParties = $this->candidate->getPoliticalParties();

        return view('candidate.register_candidate', compact('politicalParties'));
    }

    /**
     * @param Request $request
     * @return $this|RedirectResponse
     */
    public function store(Request $request)
    {
        $arrayCandidate = $request->all();
        $validationRules = $this->candidate->getValidationRules();

        $validator = Validator::make($arrayCandidate, $validationRules);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        $imageName = $this->saveImage($request);
        $arrayCandidate['image'] = $imageName ?? 'default.jpg';

        $this->candidateRepository->create($arrayCandidate);

        Toastr::success('Se agregó candidato correctamente', 'Candidato');

        return redirect()->route('candidato.index');
    }

    /**
     * @param $id
     * @return View
     */
    public function edit($id)
    {
        $candidate = $this->candidateRepository->findById($id);
        $politicalParties = $this->candidate->getPoliticalParties();

        return view('candidate.edit_candidate',[
            'candidate' => $candidate,
            'political_parties' => $politicalParties,
        ]);
    }

    /**
     * @param Request $request
     * @param $id
     * @return $this|RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $arrayCandidate = $request->all();

        $validationRules = $this->candidate->getValidationRules();
        $validationRules['email'] = 'required|email';
        $validationRules['dni'] = 'required|digits_between:7,8|numeric';

        $messages = $this->candidate->getValidationMessages();

        $validator = Validator::make($arrayCandidate, $validationRules, $messages);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }

        $imageName = $this->saveImage($request);
        $arrayCandidate['image'] = $imageName ?? 'default.jpg';

        $this->candidateRepository->update($arrayCandidate, $id);

        Toastr::info('Se edito correctamente', 'Candidato');

        return redirect()->route('candidato.index');
    }

    /**
     * @param $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        $candidate = $this->candidateRepository->findById($id);

        if ($candidate->getAttribute('first_name') === 'WhiteVote'){
            Toastr::warning('Este candidato no se puede eliminar');

            return back();
        }

        $this->candidateRepository->delete($id);

        Toastr::success('Se elimino correctamente', 'Candidato');

        return redirect()->route('candidato.index');
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function searchByFilter(Request $request)
    {
        if ($request->filter === 'Filtro' || $request->param === null){
            Toastr::warning('Revise los parametros de busqueda', 'Buscar');

            return redirect()->route('candidato.index');
        }

        $candidates = $this->candidateRepository->findByFilter($request->filter, $request->param);

        if ($candidates->isEmpty()){
            Toastr::info('No se encontraron coincidencias');

            return redirect()->route('candidato.index');
        }

        return view('candidate.list_candidate', compact('candidates'));
    }

    private function saveImage(Request $request): ?string
    {
        $fileName = null;

        if (isset($request->image)) {
            $file = $request->file('image');
            $fileName= $file->getClientOriginalName();
            $file->storeAs('',$fileName, 'candidates');
        }

        return $fileName;
    }

    public function candidatesIndex(): View
    {
        $candidates =  $this->candidateRepository->getAll();

        return view('principal', ['candidates' => $candidates]);
    }

    public function searchWinnerCandidate(): View
    {
        $candidate = $this->candidate->getWinnerCandidate();
        $candidate = $this->candidateRepository->findById($candidate->id);

        // Cambio en config el status de la votacion
        session(['voting_status' => false]);

        return view ('candidate.winner_view', compact('candidate'));
    }
}

resources/views/candidate/edit_candidate.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <h1>Candidato</h1>
        <hr style= "background-color: black;"/>
        <form action="{{route('candidato.update', $candidate->id) }}" enctype="multipart/form-data" method="POST" type="file">
            @csrf
            @method('patch')
            <label for="">
                Nombre
                <input class="form-control" type="text" name="first_name" value="{{$candidate->first_name}}">
                {!! $errors->first('first_name','<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Apellido
                <input class="form-control" type="text" name="last_name" value="{{$candidate->last_name}}">
                {!! $errors->first('last_name', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Fecha de nacimiento
                <input class="form-control" type="date" name="birthday" value="{{$candidate->birthday}}">
                {!! $errors->first('birthday', '<span class=error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                DNI
                <input class="form-control" type="text" name="dni" value="{{$candidate->dni}}">
                {!! $errors->first('dni', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Direccion
                <input class="form-control" type="text" name="address" value="{{$candidate->address}}">
                {!! $errors->first('address', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Email
                <input class="form-control" type="email" name="email" value="{{$candidate->email}}">
                {!! $errors->first('email', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Lista
                <input class="form-control" type="text" name="list" value="{{$candidate->list}}">
                {!! $errors->first('list', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Partido Politico
                <select name="political_party">
                    @foreach($political_parties as $party)
                        @if($party == $candidate->political_party)
                            <option selected value="{{$party}}">{{$party}}</option>
                        @else
                            <option value="{{$party}}">{{$party}}</option>
                        @endif
                    @endforeach
                </select>
                {!! $errors->first('political_party', '<span class=error>:message</span>') !!}
            </label>
            <br>
            <label for="image">
                Imagen Perfil
                <img src="{{ asset('images/candidate/' . $candidate->image) }}" alt="" class="rounded" width="20%">
                <input type="file" class="form-control" name="image">
                {!! $errors->first('image', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <input class="btn btn-primary" type="submit" value="{{ 'Guardar' }}">
            <a href="{{ route('candidato.index') }}" class="btn btn-danger">{{ 'Cancelar' }}</a>
        </form>
        <hr>
    </div>
@endsection

resources/views/candidate/list_candidate.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        {{--Navbar de busqueda y crear candidato--}}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand">Candidatos</a>
            <ul class="navbar-nav">
                <li>
                    <form class="form-inline my-2 my-lg-0" method="post" action="{{route('candidate.searchByFilter')}}">
                        @csrf
                        <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search" name="param">
                        <div class="input-group mr-sm-2">
                            <select class="custom-select" id="inputGroupSelect01" name="filter">
                                <option selected>Filtro</option>
                                <option value="first_name">Nombre</option>
                                <option value="last_name">Apellido</option>
                                <option value="dni">DNI</option>
                            </select>
                        </div>
                        <button class="btn btn-outline-info my-2 my-sm-2" type="submit">Buscar</button>
                    </form>
                </li>
                <li>
                    <div class="my-sm-2">
                        <a class="btn btn-success float-right ml-sm-2" href="{{ route('candidato.create')}}">
                            Agregar
                        </a>
                    </div>
                </li>
            </ul>
        </nav>
        {{--Tabla de Candidatos--}}
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">Fecha de Nacimiento</th>
                <th scope="col">DNI</th>
                <th scope="col">Direccion</th>
                <th scope="col">Lista</th>
                <th scope="col">Partido Politico</th>
                <th scope="col">Email</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
                @foreach($candidates as $candidate)
                    <tr>
                        <td>{{$candidate->first_name}}</td>
                        <td>{{$candidate->last_name}}</td>
                        <td>{{$candidate->birthday}}</td>
                        <td>{{$candidate->dni}}</td>
                        <td>{{$candidate->address}}</td>
                        <td>{{$candidate->list}}</td>
                        <td>{{$candidate->political_party}}</td>
                        <td>{{$candidate->email}}</td>
                        <td><a class="btn btn-warning" href="{{ route('candidato.edit', $candidate->id) }}">Editar</a></td>
                        <td>
                            <form style="display:inline;" action="{{ route('candidato.destroy', $candidate->id) }}" method="POST">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger" type="submit">Eliminar</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/candidate/register_candidate.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <h1>Candidato</h1>
        <hr style= "background-color: black;"/>
        <form action="{{route('candidato.store')}}" enctype="multipart/form-data" method="POST" type="file">
            @csrf
            <label for="">
                Nombre
                <input class="form-control" type="text" name="first_name" value="{{ old('first_name') }}">
                {!! $errors->first('first_name','<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Apellido
                <input class="form-control" type="text" name="last_name" value="{{ old('last_name') }}">
                {!! $errors->first('last_name', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Fecha de nacimiento
                <input class="form-control" type="date" name="birthday" value="{{ old('birthday') }}">
                {!! $errors->first('birthday', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                DNI
                <input class="form-control" type="text" name="dni" value="{{ old('dni') }}">
                {!! $errors->first('dni', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Direccion
                <input class="form-control" type="text" name="address" value="{{ old('address') }}">
                {!! $errors->first('address', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Email
                <input class="form-control" type="email" name="email" value=" {{ old('email') }}">
                {!! $errors->first('email', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Lista
                <input class="form-control" type="text" name="list" value="{{ old('list') }}">
                {!! $errors->first('list', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Partido Politico
                <select name="political_party">
                    @foreach($politicalParties as $party)
                        <option value="{{$party}}">{{$party}}</option>
                    @endforeach
                </select>
                {!! $errors->first('political_party', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <label for="image">
                Imagen Perfil
                <input type="file" class="form-control" name="image" value="{{ old('image') }}">
                {!! $errors->first('image', '<span class=text-danger error>:message</span>') !!}
            </label>
            <br>
            <input class="btn btn-primary" type="submit" value="{{ 'Guardar' }}">
            <a class="btn btn-danger" href="{{ route('candidato.index') }}">Cancelar</a>
        </form>
        <hr>
    </div>
@endsection

resources/views/candidate/winner_view.blade.php
@extends('layouts.app')
@section('content')
    <div class="text-center">
        <h1>Candidato Electo</h1>
    </div>
    <div class="container-fluid text-center">
        <div class="d-inline-block" style="width: 25rem;">
            <div class="m-4 pr-lg-5 pl-lg-5" >
                <div class="border">
                    <img class="card-img-top" src="{{ asset('images/candidate/' . $candidate->image) }}">
                    <div class="card-body text-left">
                        <h5 class="card-title">{{$candidate->first_name}} {{$candidate->last_name}}</h5>
                        <p class="card-text">{{$candidate->political_party}}</p>
                        <p class="card-text">{{$candidate->list}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="chart-div" class="d-flex justify-content-center">
        <?= \App\Charts\Chart::getInstance()
            ->getBarChartCandidate()
            ->render('BarChart', 'Estadisticas de votos', 'chart-div')?>
    </div>
@endsection