routes/web.php
<?php
/*
 *
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Home */
Route::get('/', 'PrincipalController@index');
Route::post('/votar', 'PrincipalController@createVoteAndUpdateStatusVoter')->name('principal.createVoteAndUpdateStatusVoter');
Route::post('/buscar', 'PrincipalController@voterSearch')->name('principal.voterSearch');

/* Voter Resource*/
Route::resource('votante', 'VoterController')->except(['destroy']);
Route::post('/votante/buscar', 'VoterController@searchByFilter')->name('voters.searchByFilter');

/*Candidate Resource*/
Route::resource('candidato', 'CandidateController')->except(['show']);
Route::get('/candidatos/listar', 'CandidateController@listCandidates')->name('candidate.list');
Route::post('/candidato/buscar','CandidateController@searchByFilter')->name('candidate.searchByFilter');

/* Authentication Routes*/
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

/* Last View Route*/
Route::get('/ganador', 'CandidateController@searchWinnerCandidate')->name('candidate.searchWinner');

app/Voter.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

/**
 * App\Voter
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $dni
 * @property string $address
 * @property string $status
 * @property string $email
 * @property string $birthday
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Voter whereAddress($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Voter whereBirthday($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Voter whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Voter whereDni($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Voter whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Voter whereFirstName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Voter whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Voter whereLastName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Voter whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Voter whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 */
class Voter extends Model
{
    use Notifiable;

    protected $fillable = [
        'first_name', 'last_name','birthday','dni','address','status','email',
    ];

    public function canVote(): bool
    {
        return ($this->status !== '1');
    }

    /**
     * @param $voter_dni
     * @return Model|null|object|static
     */
    public function findVoterByDNI($voter_dni){
        return Voter::whereDni($voter_dni)->first();
    }
}

app/Http/Controllers/VoterController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\VoterRequest;
use App\Http\Requests\VoterUpdateRequest;
use App\Repositories\Repository;
use App\Voter;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class VoterController extends Controller
{
    private $voterRepository;

    public function __construct(Voter $voter)
    {
        $this->middleware('auth');
        $this->voterRepository = new Repository($voter);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|View
     */
    public function index()
    {
        $voters = $this->voterRepository->getAllPaginated(10);
        return view('voter.list_voter', compact('voters'));
    }

    /**
     * @return View
     */
    public function create()
    {
        return view('voter.register_voter');
    }

    /**
     * @param VoterRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(VoterRequest $request)
    {
        if (! $this->verifyAge($request->input('birthday'))) {

            return back()->with('age', 'Menor de edad');
        }

        $arrayVoter = $request->all();
        $arrayVoter['status'] = 0;
        $this->voterRepository->create($arrayVoter);

        Toastr::success('Se agrego votante correctamente', 'Votante');

        return redirect()->route('votante.index');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|View
     */
    public function edit($id)
    {
        $voter = $this->voterRepository->findById($id);

        return view('voter.edit_voter', compact('voter'));
    }

    /**
     * @param VoterUpdateRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(VoterUpdateRequest $request, $id)
    {
        $this->voterRepository->update($request->all(), $id);

        Toastr::success('Se edito correctamente', 'Votante');

        return redirect()->route('votante.index');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|RedirectResponse|View
     */
    public function searchByFilter(Request $request)
    {
        if ($request->filter === 'Filtro' || $request->search === null){
            Toastr::warning('Revise los parametros de busqueda', 'Buscar');

            return redirect()->route('votante.index');
        }

        $voters = $this->voterRepository->findByFilter($request->filter, $request->search);
        if ($voters->isEmpty()){
           Toastr::info('No se encontraron coincidencias');
           
           return redirect()->route('votante.index');
       }

        return view('voter.list_voter', compact('voters'));
    }

    public function voterIndex(): View
    {
        $voter = $this->voterRepository->getAll();

        return view('principal', ['voter' => $voter]);
    }

    private function verifyAge($date): bool
    {
        $arrayDate = date_parse($date);
        $age = Carbon::createFromDate($arrayDate['year'],$arrayDate['month'], $arrayDate['day'])->age;

        return ($age > 18);
    }
}

resources/views/voter/edit_voter.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <h1> Votante </h1>
        <hr style="background-color: #1b1e21">
        <form action="{{ route('votante.update',$voter->id) }}" method="POST">
            @csrf
            @method('patch')
            <br>
            <label for="">
                Nombre
                <input class="form-control" type="text" name="first_name" value="{{$voter->first_name}}">
                {!! $errors->first('first_name','<span class=error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Apellido
                <input class="form-control" type="text" name="last_name" value="{{$voter->last_name}}" >
                {!! $errors->first('last_name','<span class=error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Fecha de nacimiento
                <input class="form-control" type="date" name="birthday" value="{{$voter->birthday}}" >
                {!! $errors->first('birthday','<span class=error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Dni
                <input class="form-control" type="text" name="dni" value="{{$voter->dni }}" >
                {!! $errors->first('dni','<span class=error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Direccion
                <input class="form-control" type="text" name="address" value="{{$voter->address }}" >
                {!! $errors->first('address','<span class=error>:message</span>') !!}
            </label>
            <br>
            <label for="">
                Email
                <input class="form-control" type="email" name="email" value="{{$voter->email }}" >
                {!! $errors->first('email', '<span class=error>:message</span>') !!}
            </label>
            <br>
            <input class="btn btn-primary" type="submit" value="{{ 'Guardar ' }}">
            <a class="btn btn-danger" href="{{ route('votante.index') }}">Cancelar</a>

        </form>
        <hr>
    </div>
@endsection

resources/views/voter/list_voter.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        {{--Navbar de busqueda y crear votante--}}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand">Votantes</a>
            <ul class="navbar-nav">
                <li>
                    <form class="form-inline my-2 my-lg-0" method="post" action="{{route('voters.searchByFilter')}}">
                        @csrf
                        <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search" name="search">
                        <div class="input-group mr-sm-2">
                            <select class="custom-select" id="inputGroupSelect01" name="filter">
                                <option selected>Filtro</option>
                                <option value="first_name">Nombre</option>
                                <option value="last_name">Apellido</option>
                                <option value="dni">DNI</option>
                            </select>
                        </div>
                        <button class="btn btn-outline-info my-2 my-sm-2" type="submit">Buscar</button>
                    </form>
                </li>
                <li>
                    <div class="form-inline my-sm-2">
                        <a class="btn btn-success float-right ml-sm-2" href="{{ route('votante.create')}}">
                            Agregar
                        </a>
                    </div>
                </li>
            </ul>
        </nav>
        {{--Tabla de Votantes--}}
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col">Nombre </th>
                <th scope="col">Apellido </th>
                <th scope="col">Fecha de Nacimiento</th>
                <th scope="col">DNI</th>
                <th scope="col">Direccion</th>
                <th scope="col">Email</th>
                <th></th>
            </tr>
            </thead>

            @foreach ($voters as $voter)
                <tr>
                    <td>{{ $voter->first_name }}</td>
                    <td>{{ $voter->last_name }}</td>
                    <td>{{$voter->birthday}}</td>
                    <td>{{ $voter->dni }}</td>
                    <td>{{$voter->address}}</td>
                    <td>{{$voter->email}}</td>
                    <td><a class="btn btn-warning" href="{{ route('votante.edit', $voter->id) }}">Editar</a></td>
                </tr>
            @endforeach
        </table>
        {{ $voters->links() }}
    </div>
@endsection

resources/views/voter/register_voter.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <h1>Votante</h1>
        <hr style="background-color: #1b1e21">
        @if (session()->has('age'))
            <div class="alert alert-danger" role="alert">
                {{ session('age') }}
            </div>
        @endif
        <form action="{{ route('votante.store') }}" method="POST">
            @csrf
            <label for="">
                Nombre
                <input class="form-control" type="text" name="first_name" value="{{ old('first_name') }}">
                {!! $errors->first('first_name','<span class="text-danger error">:message</span>') !!}
            </label>
            <br>
            <label for="">
                Apellido
                <input class="form-control" type="text" name="last_name" value="{{ old('last_name') }}">
                {!! $errors->first('last_name','<span class="text-danger error">:message</span>') !!}
            </label>
            <br>
            <label for="">
                Fecha de nacimiento
                <input class="form-control" type="date" name="birthday" value="{{ old('birthday') }}">
                {!! $errors->first('birthday','<span class="text-danger error">:message</span>') !!}
            </label>
            <br>
            <label for="">
                Dni
                <input class="form-control" type="text" name="dni" value="{{ old('dni') }}">
                {!! $errors->first('dni','<span class="text-danger error">:message</span>') !!}
            </label>
            <br>
            <label for="">
                Dirección
                <input class="form-control" type="text" name="address" value="{{ old('address') }}">
                {!! $errors->first('address','<span class="text-danger error">:message</span>') !!}
            </label>
            <br>
            <label for="">
                Email
                <input class="form-control" type="email" name="email" value="{{ old('email') }}">
                {!! $errors->first('email', '<span class="text-danger error">:message</span>') !!}
            </label>
            <br>
            <input class="btn btn-primary" type="submit" value="{{ 'Guardar' }}">
            <a class="btn btn-danger" href="{{ route('votante.index') }}">Cancelar</a>
        </form>
        <hr>
    </div>
@endsection