routes/web.php
<?php
/*
 *
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Home */
Route::get('/', 'PrincipalController@index');
Route::post('/votar', 'PrincipalController@createVoteAndUpdateStatusVoter')->name('principal.createVoteAndUpdateStatusVoter');
Route::post('/buscar', 'PrincipalController@voterSearch')->name('principal.voterSearch');

/* Voter Resource*/
Route::resource('votante', 'VoterController')->except(['destroy']);
Route::post('/votante/buscar', 'VoterController@searchByFilter')->name('voters.searchByFilter');

/*Candidate Resource*/
Route::resource('candidato', 'CandidateController')->except(['show']);
Route::get('/candidatos/listar', 'CandidateController@listCandidates')->name('candidate.list');
Route::post('/candidato/buscar','CandidateController@searchByFilter')->name('candidate.searchByFilter');

/* Authentication Routes*/
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

/* Last View Route*/
Route::get('/ganador', 'CandidateController@searchWinnerCandidate')->name('candidate.searchWinner');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/jquery.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container-fluid">
            @if(!Auth::check())
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            @else
                <a class="navbar-brand" href="{{ url('/home') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            @endif
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    @guest
                        <li class="nav-item">
                            <a class="nav-link float-left" href="{{ url('/') }}">{{ __('Inicio') }}</a>
                        </li>
                    @else
                        <li class="nav-item">
                            <a class="nav-link float-left" href="{{ route('candidato.index') }}">{{ __('Candidatos') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('votante.index') }}">{{ __('Votantes') }}</a>
                        </li>
                    @endguest
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Ingresar') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Registrarse') }}</a>
                        </li>
                    @else
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                {{ __('Cerrar Sesion') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
<script src="{{ asset('js/app.js') }}"></script>
{!! Toastr::message() !!}
</body>
</html>